name: surat_apk_whatsapp_ig
description: Surat generator Android (UI mirip WhatsApp Business, warna gaya Instagram).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  printing: ^5.13.4
  pdf: ^3.11.0
  qr_flutter: ^4.1.0
  share_plus: ^10.0.0
  uuid: ^4.5.1
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/lebak.png
